image: php:7.1-cli
clone:
  depth: 1
pipelines:
  branches:
    master:
      - step:
          # The initial test step will simply check or the components still pass all their unit tests. Since these
          # Are used by all the other items in the heavyd tool.
          name: Validating "components" package
          caches:
            - composer
          # @TODO Setup a more optimized container instead of the full apache one.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - ./vendor/bin/phing packages:components-install -buildfile build.test.xml
            - ./vendor/bin/phing packages:components-phpunit -buildfile build.test.xml
          artifacts:
            - packages/**
      - step:
          # This test will validate the various builds from the seeder. Which will ensure all the
          # builds from the seeder are functional.
          name: Validating "seeder" package
          caches:
            - composer
          # @TODO Setup a more optimized container instead of the full apache one.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - git config --global user.email "pipeline@test.com"
            - git config --global user.name "Pipeline"
            - composer install
            - ./vendor/bin/phing packages:seeder-install -buildfile build.test.xml
            - ./vendor/bin/phing packages:seeder-prepare-builds -buildfile build.test.xml -Ddir.seeder.build=/opt/atlassian/pipelines/agent/build/packages/seeder/build/default-d8
            - ./vendor/bin/phing packages:seeder-phpunit -buildfile build.test.xml
          artifacts:
            - packages/**
      - step:
          # Update the documentation by deploying the html to the online location.
          name: Updating documentation
          caches:
            - composer
          # @TODO Setup a more optimized container instead of the full apache one.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            # Places the default bitbucket id in the predictable location to make life easier for all the
            # subsequent commands (rsync etc).
            - ln -s /opt/atlassian/pipelines/agent/data/id_rsa ~/.ssh/id_rsa
            - composer install
            - ./vendor/bin/phing document -f build.docs.xml
            - ./vendor/bin/dep deploy-dev docs
          artifacts:
            - packages/**
